apiVersion: v1
kind: Secret
metadata:
  name: roboshop-secret
type: Opaque
data:
  username: cm9ib3Nob3AK 
  password: cm9ib3Nob3AxMjMK

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec: 
  containers:
  - name: secret-container
    image: nginx
    envfrom: 
    - secretRef:
        name: roboshop-secret
