apiVersion: v1
kind: Namespace
metadata:
  name: roboshop

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-namespace
  namespace: roboshop
spec:
  containers:
  - name: frontend-namespace
    image: nginx
    ports:
    - containerPort: 80    