# create deployment with nginx as image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: roboshop
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx-apps
        image: nginx:1.31.2-perl
  strategy:
    type: Recreate