- name: Install Python and build dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ package }}"  


- name: Creating "{{ AppUser }}" user
  ansible.builtin.user:
      name: "{{ AppUser }}"
      state: present

- name: cleaning the "{{ AppDirectory }}"
  ansible.builtin.file:
        path: "{{ AppDirectory }}"
        state: absent
       
- name: Creating the "{{ AppDirectory }}"
  ansible.builtin.file:
      path: "{{ AppDirectory }}"
      state: directory

- name: Download and extract archive from URL
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ AppDirectory }}"
    remote_src: yes

- name: Install Python dependencies from requirements.txt
  ansible.builtin.pip:
    requirements: "{{ AppDirectory }}"/requirements.txt
    chdir: "{{ AppDirectory }}"

- name: Copying the template file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"



- name: Starting {{ component }} service
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Configuring the hostName
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }}   


     



  