- name: Disabling {{ package }} default version
  ansible.builtin.shell: dnf module disable "{{ package }}" -y

- name: Disabling {{ package }} default version
  ansible.builtin.shell: dnf module enable "{{ package }}":"{{ packageversion }}" -y


- name: Installing "{{ package }}"
  ansible.builtin.dnf:
      name: "{{ package }}"
      state: present

- name: Creating app user and app directory for {{ component }} service
  ansible.builtin.include_role:
    name: common
    include_tasks: createUser&App

- name: Generating artifact dependencies for {{ component }} service
  community.general.npm:
    path: "{{ AppDirectory }}" 

#This task is only required for catalogue component and not for cart or user component
- name: Injecting Mongodb schema for {{ component }} service
  ansible.builtin.include_role:
    name: common
    include_tasks: injectMongoSchema
  when: setup_mongodb_schema is defined

- name: Configure the {{ component }} service
  ansible.builtin.include_role:
    name: common
    include_tasks: configureService    


- name: Configuring the hostName
  ansible.builtin.include_role:
    name: common
    include_tasks: setHostname.yml


     



  