package: 
      - "python3"
      - "python3-devel"
      - "gcc"
      - "python3-pip"
      - "python3-setuptools"
url: "https://stan-robotshop.s3.amazonaws.com/payment-v3.zip"
AppUser: "roboshop"
AppDirectory: "/app"
component: "payment"
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop/data/{{ env }} token={{ token }} url=http://http://vault-tools.bihamlanet.store:8200/ validate_certs=false') }}"
