- name: copying  repo file
  ansible.builtin.copy:
    src: "{{ component }}".repo
    dest: /etc/yum.repos.d/"{{ package }}".repo

- name: installing "{{ package }}"
  ansible.builtin.dnf:
    name: "{{ package }}"
    state: present

- name: Starting "{{ package }}" service
  ansible.builtin.service:
      name: mongod
      state: started
      enabled: true       

# - name: configuring the hostname
#   ansible.builtin.shell: set-hostname "{{ component }}"-"{{ env }}"      